<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WastelandStory</AssemblyName>
    <RootNamespace>WastelandStory</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.companyname.wastelandstory</ApplicationId>
    <ApplicationTitle>WastelandStory</ApplicationTitle>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <AndroidSupportedAbis>arm64-v8a</AndroidSupportedAbis>
    <CSharpShellApkUseDebugKey>True</CSharpShellApkUseDebugKey>
    <CSharpShellApkSignatureSchemes>V2, V3</CSharpShellApkSignatureSchemes>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Survivalcraft">
      <HintPath>/storage/emulated/0/Download/.SC2-Mod 🔰/References/API/SC2 v2.4 API 1.9.3.1/Survivalcraft.dll</HintPath>
    </Reference>
    <Reference Include="EntitySystem">
      <HintPath>/storage/emulated/0/Download/.SC2-Mod 🔰/References/API/SC2 v2.4 API 1.9.3.1/EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Engine">
      <HintPath>/storage/emulated/0/Download/.SC2-Mod 🔰/References/API/SC2 v2.4 API 1.9.3.1/Engine.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>